$ErrorActionPreference = 'Stop'

$root = (Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$version = (Get-Content (Join-Path $root 'VERSION') -Raw).Trim()
$pluginDir = Join-Path $root 'plugin'
$manifest = Join-Path $pluginDir 'manifest.json'
$releaseDir = Join-Path $root 'release-assets'
$buildDir = Join-Path $root '.build/uxp-package'
$verifyDir = Join-Path $root '.build/uxp-verify'
$target = Join-Path $releaseDir "PS-Sezhao-Photoshop-v$version.ccx"

Remove-Item $buildDir -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item $verifyDir -Recurse -Force -ErrorAction SilentlyContinue
Remove-Item $target -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Force $buildDir | Out-Null
New-Item -ItemType Directory -Force $releaseDir | Out-Null

$officialPackage = $null
$cliSucceeded = $false
$cliScript = $env:UXP_CLI_JS

if ($cliScript -and (Test-Path $cliScript)) {
    Write-Host "Packaging with Adobe UXP CLI source: $cliScript"
    & node $cliScript plugin package --manifest $manifest --apps PS --outputPath $buildDir
    if ($LASTEXITCODE -eq 0) {
        $officialPackage = Get-ChildItem -Path $buildDir -Filter '*.ccx' -File -Recurse | Select-Object -First 1
        $cliSucceeded = [bool]$officialPackage
    } else {
        Write-Warning "Adobe UXP CLI returned exit code $LASTEXITCODE; using the standards-compatible CCX fallback."
    }
} elseif (Get-Command uxp -ErrorAction SilentlyContinue) {
    Write-Host 'Packaging with the installed Adobe uxp command.'
    & uxp plugin package --manifest $manifest --apps PS --outputPath $buildDir
    if ($LASTEXITCODE -eq 0) {
        $officialPackage = Get-ChildItem -Path $buildDir -Filter '*.ccx' -File -Recurse | Select-Object -First 1
        $cliSucceeded = [bool]$officialPackage
    } else {
        Write-Warning "Installed Adobe UXP CLI returned exit code $LASTEXITCODE; using the standards-compatible CCX fallback."
    }
} else {
    Write-Warning 'Adobe UXP CLI is unavailable; using the standards-compatible CCX ZIP fallback.'
}

if ($cliSucceeded) {
    Copy-Item $officialPackage.FullName $target -Force
    Write-Host 'CCX was generated by Adobe UXP CLI.'
} else {
    Add-Type -AssemblyName System.IO.Compression.FileSystem
    $temporaryZip = Join-Path $buildDir 'PS-Sezhao-Photoshop.zip'
    Remove-Item $temporaryZip -Force -ErrorAction SilentlyContinue
    [System.IO.Compression.ZipFile]::CreateFromDirectory(
        $pluginDir,
        $temporaryZip,
        [System.IO.Compression.CompressionLevel]::Optimal,
        $false
    )
    Move-Item $temporaryZip $target -Force
    Write-Host 'CCX was generated as a standards-compatible ZIP package with the plugin files at archive root.'
}

if (-not (Test-Path $target) -or (Get-Item $target).Length -le 0) {
    throw 'Generated Photoshop .ccx is missing or empty.'
}

$tempZip = Join-Path $root '.build/PS-Sezhao-Photoshop-package.zip'
Remove-Item $tempZip -Force -ErrorAction SilentlyContinue
Copy-Item $target $tempZip -Force
Expand-Archive -Path $tempZip -DestinationPath $verifyDir -Force
if (-not (Test-Path (Join-Path $verifyDir 'manifest.json'))) {
    throw 'Generated .ccx does not contain manifest.json at its root.'
}

$verifiedManifest = Get-Content (Join-Path $verifyDir 'manifest.json') -Raw | ConvertFrom-Json
if ($verifiedManifest.version -ne $version) {
    throw "Generated CCX manifest version $($verifiedManifest.version) does not match VERSION $version."
}
if ($verifiedManifest.host.app -ne 'PS') {
    throw 'Generated CCX does not target Photoshop.'
}

Write-Host "Built and verified Photoshop CCX: $target"
Get-Item $target | Format-List Name, Length, FullName
